var tag = document.getElementById('a1');
function verify() {
    var username = document.getElementById('Username1').value;
    var users = fetch('http://localhost:3000/registeruser');
    users.then(res => res.json()).then(res => {
        for (let i = 0; i < res.length; i++) {

            let vs = res[i].email;
            if (vs == username && username!='') {
                tag.innerHTML = `<div class="field">
               <svg class="input-icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
               viewBox="0 0 16 16">
               <path
                 d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z">
               </path>
             </svg>
             <input placeholder=" Enter New Password" id="Password1" minlength="8" class="input-field" type="password">
             </div> <br>
             <div class="field">
               <svg class="input-icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
               viewBox="0 0 16 16">
               <path
                 d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z">
               </path>
             </svg>
             <input placeholder=" Confirm New Password" minlength="8" id="confirm_Password" class="input-field" type="password">
             </div>
             <span id="displaymsz"></span>`
                document.getElementById('changebtn').innerHTML = ` <button class="button1" onclick="savepassword()" type="submit">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button>`
                var tag1 = document.getElementById('displaymsz1');
                tag1.innerText = ``
            } else {
                var tag1 = document.getElementById('displaymsz1');
                tag1.innerText = `Enter valid username!!`
                tag1.style.color = `red`;
            }
        }
    });
    event.preventDefault();
    // to stop the unwanted message/behaviours generated by the browser.
}
function savepassword() {
    var username1 = document.getElementById('Username1').value;
    var Password1 = document.getElementById('Password1').value;
    var confirm_Password = document.getElementById('confirm_Password').value;
    var users = fetch('http://localhost:3000/registeruser');
    users.then(res => res.json()).then(res => {
        if (Password1 === confirm_Password) {
            for (let i = 0; i < res.length; i++) {
                let vs = res[i].email;
                var id = res[i].id;
                if (vs == username1) {
                    fetch(`http://localhost:3000/registeruser/${id}`, {
                        method: "PUT",
                        body: JSON.stringify({
                            First_Name: res[i].First_Name,
                            last_name: res[i].last_name,
                            email: res[i].email,
                            password: Password1,
                            confirm_password: Password1
                        }),
                        headers: {
                            "content-Type": "application/json"
                        }
                    }
                    )
                }
            }
            setTimeout(delays, 20)
            function delays() {
                window.location.href = '../hmtlfiles/login.html';
            }
        } else {
            var tag1 = document.getElementById('displaymsz');
            tag1.innerText = `Miss Match in Password`
            tag1.style.color = `red`;
        }
    });
    event.preventDefault();
}
